name: BFEX
channels:
- defaults
dependencies:
- flask=0.12.2
- pip=9.0.1
- python=3.6.4
- beautifulsoup4=4.6.0
- pip:
  - aniso8601==2.0.0
  - chardet==3.0.4
  - elasticsearch==6.1.1
  - elasticsearch-dsl==6.1.0
  - flask-restful==0.3.6
  - idna==2.6
  - ipaddress==1.0.19
  - marshmallow==3.0.0b7
  - python-dateutil==2.6.1
  - pytz==2017.3
  - requests==2.18.4
  - six==1.11.0
  - urllib3==1.22

