version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - checkout

      - run:
          name: Build Docker Containers
          command: docker-compose build

      - run:
          name: Remove Current Containers
          command: docker-compose down

      - run: 
          name: Run Docker Containers
          command: |
            docker-compose up -d

            # Give time for services to start
            sleep 20

      - run:
          name: Run Tests
          command: |
            DOCKERID=$(docker ps -aqf "name=project_bfex_1")
            docker exec $DOCKERID /opt/conda/envs/BFEX/bin/py.test test

      - run:
          name: Shutdown Docker Containers
          command: |
            docker-compose down
      # - add_ssh_keys

      # - run:
      #     name: Add Known Hosts
      #     command: |
      #       set -x
      #       ssh-keyscan ${DEPLOY_IP} > ~/.ssh/known_hosts

      # - run:
      #     name: Deploy
      #     command: |
      #       set -x
      #       rsync -avr -e ssh --exclude=".*/" . ${DEPLOY_USER}@${DEPLOY_IP}:~/BFEX
      #       ssh ${DEPLOY_USER}@${DEPLOY_IP} << EOF
      #         cd BFEX;
      #         sudo docker-compose down --remove-orphans
      #         sudo docker-compose build
      #         sudo docker-compose up -d
      #       EOF